### ISSUE TITLE
Deployment on AWS

### ISSUE THREAD

**Issue by Pierozi** [hoaproject/Contributions-Provisioning#3]
We have recently choose to go with Amazon hosting solution.
In the Infrastructure as a code solution, we will need be able to deploy our Servers easily.

Important to remind the Workflow :
1. Packer used for build our own distrib
2. Packer provision our build with [Services scripted](https://github.com/hoaproject/Contributions-Provisioning/issues/2)
3. Packer run `AMI` builder for have an image ready to use and already provisioned
4. Use deployment script for run a new `EC2` instance based on `AMI`.

This deployment script can be done with `PHP` script, with `Hoa\Console` and `AWS SDK`

**Comment by Pierozi** [comment]
Oups, wrong repository, moved in https://github.com/hoaproject/Infrastructure/issues/3

**Comment by Hywan** [comment]
Never mind, we should work on this too, but maybe this will be done in the infra and can be backported here after.
